import { projectCategories, projectLearningPaths, projects, type Language, type ProjectLearningStep } from "../content/site";
import { MathFormula } from "../components/MathFormula";

const statusLabel = { completed: { en: "Completed", zh: "已完成" }, "in-progress": { en: "In Progress", zh: "进行中" }, planned: { en: "Planned", zh: "规划中" }, live: { en: "Live Portfolio", zh: "在线作品集" } };
const legacyProjectSlugs: Record<string, string> = {
  "experimentation-platform": "ecommerce-product-analytics-experimentation",
  "real-time-fraud-risk-decisioning": "production-fraud-risk-decision-system",
};
const fraudProjectMap = [
  { title: { en: "1. Decision framing", zh: "1. 明确决策问题" }, input: { en: "A transaction and asymmetric costs", zh: "一笔交易与不对称成本" }, work: { en: "Define approve, review, and decline as the business actions—not just a fraud label.", zh: "将批准、人工审核和拒绝定义为业务动作，而不只是预测欺诈标签。" }, output: { en: "A cost-sensitive decision objective", zh: "成本敏感的决策目标" } },
  { title: { en: "2. Time-safe data", zh: "2. 时间安全的数据" }, input: { en: "590,540 IEEE-CIS transactions", zh: "590,540 条 IEEE-CIS 交易" }, work: { en: "Engineer behavior-relative features, then split train / validation / test in chronological order.", zh: "构建相对历史行为的特征，再按时间顺序切分训练、验证和测试集。" }, output: { en: "A future-like holdout with no tuning leakage", zh: "不含调参泄漏、近似未来场景的留出集" } },
  { title: { en: "3. Establish a baseline", zh: "3. 建立基线" }, input: { en: "The same features and time split", zh: "相同特征与时间切分" }, work: { en: "Fit Logistic Regression before LightGBM so extra complexity has a transparent reference.", zh: "先拟合逻辑回归，再使用 LightGBM，使额外复杂度有透明参照。" }, output: { en: "Comparable ranking and probability metrics", zh: "可比较的排序与概率指标" } },
  { title: { en: "4. Learn nonlinear fraud signals", zh: "4. 学习非线性欺诈信号" }, input: { en: "Cleaned features plus fraud labels", zh: "清洗后的特征与欺诈标签" }, work: { en: "Train LightGBM to capture interactions such as unusual amount relative to a card’s own history.", zh: "训练 LightGBM 捕捉交互，例如交易金额相对该卡历史行为的异常程度。" }, output: { en: "A probability-ranked fraud risk score", zh: "按概率排序的欺诈风险分数" } },
  { title: { en: "5. Calibrate probabilities", zh: "5. 校准概率" }, input: { en: "Validation scores and labels", zh: "验证集分数与标签" }, work: { en: "Use Platt scaling so a probability can support a cost-based threshold rather than only a rank order.", zh: "使用 Platt scaling，使概率不仅用于排序，也能支持基于成本的阈值。" }, output: { en: "Decision-ready risk probabilities", zh: "可用于决策的风险概率" } },
  { title: { en: "6. Select an operating policy", zh: "6. 选择运营策略" }, input: { en: "Calibrated validation probabilities", zh: "校准后的验证集概率" }, work: { en: "Search thresholds using missed-fraud and false-decline costs, then map risk bands to approve / review / decline.", zh: "使用漏判欺诈和误拒成本搜索阈值，再将风险区间映射到批准/审核/拒绝。" }, output: { en: "A policy tested once on the future-like test set", zh: "在近似未来测试集上只评估一次的策略" } },
  { title: { en: "7. Monitor after deployment", zh: "7. 部署后监控" }, input: { en: "Incoming features and risk scores", zh: "新进入的特征与风险分数" }, work: { en: "Track PSI, decision rates, calibration, and delayed fraud outcomes as patterns change.", zh: "在模式变化时追踪 PSI、决策比例、校准情况和延迟到来的欺诈结果。" }, output: { en: "A model system that can be challenged and maintained", zh: "可被持续检验和维护的模型系统" } },
];
const fraudDeepDive = [
  { title: { en: "1. Frame fraud as a decision problem", zh: "1. 将欺诈建模为决策问题" }, code: "src/fraud_ds/policy.py", theory: { en: "Binary classification is only an intermediate step. The model estimates risk; operations must decide whether to approve, review, or decline a transaction. A false negative loses fraud dollars, while a false positive creates customer friction and review cost.", zh: "二分类只是中间步骤。模型估计风险，运营团队必须决定批准、人工审核还是拒绝交易。假阴性会造成欺诈损失，假阳性会带来客户摩擦和审核成本。" }, implementation: { en: "Define the decision actions and the cost of each error before selecting a threshold. The repository encodes this in `evaluate_threshold`, which counts false positives and false negatives for a candidate threshold.", zh: "在选择阈值前，先定义决策动作和每类错误的成本。仓库中的 `evaluate_threshold` 会在给定阈值下统计假阳性和假阴性。" }, business: { en: "This prevents a misleading goal such as “maximize accuracy.” A risk team needs the lowest acceptable decision loss subject to customer and analyst constraints.", zh: "这避免了“最大化准确率”这种误导性目标。风险团队需要在客户体验和分析师容量约束下尽可能降低决策损失。" }, formula: { label: { en: "Decision loss", zh: "决策损失" }, latex: "C(t)=FN(t)c_{miss}+FP(t)c_{decline}", explanation: { en: "Threshold t is evaluated by the two errors it creates and their stated costs.", zh: "阈值 t 由它产生的两类错误及其明确成本共同评估。" } } },
  { title: { en: "2. Build a leakage-safe temporal dataset", zh: "2. 构建无泄漏的时间序列数据集" }, code: "src/fraud_ds/data.py → src/fraud_ds/features.py", theory: { en: "Fraud is non-stationary: attacker tactics and legitimate behavior change over time. A random row split can allow future patterns into training. Every feature must be computable using only information available before the transaction decision.", zh: "欺诈是非平稳的：攻击手法和正常用户行为会随时间变化。随机行切分可能让未来模式进入训练集。每个特征必须只能使用交易决策前已知的信息。" }, implementation: { en: "Load and merge transaction and identity data; create time and behavior-relative features; then use `temporal_split` to create the 413,378 / 88,581 / 88,581 chronological train, validation, and test partitions.", zh: "加载并合并交易与身份数据，构建时间和相对历史行为特征，再用 `temporal_split` 创建 413,378 / 88,581 / 88,581 的时间顺序训练、验证和测试分区。" }, business: { en: "The test partition simulates a future operating period. A lower but honest test metric is more useful than an inflated random-split result that fails after launch.", zh: "测试分区模拟未来运营时期。较低但真实的测试指标，比上线后失效的随机切分高指标更有价值。" } },
  { title: { en: "3. Engineer behavior-relative signals", zh: "3. 构建相对历史行为信号" }, code: "src/fraud_ds/features.py", theory: { en: "Fraud is often unusual relative to an entity’s own history, not simply large in absolute terms. Useful examples include card transaction count, card average amount, historical fraud rate, hour of day, and amount relative to card average.", zh: "欺诈通常是相对于实体自身历史的异常，而不只是绝对金额很大。有效例子包括卡片交易次数、卡片平均金额、历史欺诈率、一天中的小时数，以及金额相对卡片平均值。" }, implementation: { en: "Construct aggregates with strictly prior observations, then select numeric and categorical columns. Missing numeric values use median imputation; categoricals use most-frequent imputation and one-hot encoding with unknown categories ignored.", zh: "只使用先前观察构建聚合特征，再选择数值和类别列。缺失数值使用中位数填补；类别变量使用最常见值填补，并进行 one-hot 编码且忽略未知类别。" }, business: { en: "This turns raw events into a risk context: a $500 purchase may be ordinary for one card and anomalous for another.", zh: "这将原始事件转化为风险语境：500 美元购买对一张卡可能正常，对另一张卡却可能异常。" }, formula: { label: { en: "Relative amount feature", zh: "相对金额特征" }, latex: "r_i=\\frac{amount_i}{\\overline{amount}_{card(i)}+\\varepsilon}", explanation: { en: "A stabilised ratio expresses how unusual a transaction is for its own card history.", zh: "加入稳定项的比例表达交易相对该卡自身历史的异常程度。" } } },
  { title: { en: "4. Prove that complexity adds value", zh: "4. 证明复杂模型确实带来价值" }, code: "src/fraud_ds/train.py → src/fraud_ds/metrics.py", theory: { en: "Logistic Regression is an interpretable linear baseline: it models log-odds as a weighted sum of features. LightGBM is a gradient-boosted tree ensemble that can represent nonlinear thresholds and interactions in tabular data.", zh: "逻辑回归是可解释的线性基线：它把 log-odds 表示为特征加权和。LightGBM 是梯度提升树集成，可以表达表格数据中的非线性阈值和交互。" }, implementation: { en: "Fit the preprocessing pipeline and model on training data only. Compare the logistic baseline with balanced-class LightGBM using the identical time split. The repository reports validation PR-AUC of 0.2247 for logistic regression and 0.6312 for LightGBM.", zh: "只在训练集上拟合预处理管道和模型。在相同时间切分下比较逻辑回归基线与类别平衡的 LightGBM。仓库报告的验证集 PR-AUC 分别为 0.2247 和 0.6312。" }, business: { en: "The point is not that LightGBM is fashionable. It is that the improvement must justify more complex maintenance and monitoring.", zh: "重点不是 LightGBM 流行，而是性能提升必须足以证明更复杂维护和监控的合理性。" }, formula: { label: { en: "Logistic probability", zh: "逻辑回归概率" }, latex: "P(Y=1\\mid x)=\\sigma(\\beta_0+x^T\\beta)=\\frac{1}{1+e^{-(\\beta_0+x^T\\beta)}}", explanation: { en: "The baseline transforms a linear score into a fraud probability.", zh: "基线模型将线性分数转换为欺诈概率。" } } },
  { title: { en: "5. Evaluate ranking and probability quality separately", zh: "5. 分别评估排序质量与概率质量" }, code: "src/fraud_ds/metrics.py", theory: { en: "With 3.50% fraud prevalence, accuracy is misleading: predicting every case as legitimate is already about 96.5% accurate. PR-AUC evaluates precision-recall trade-offs among rare positive cases; ROC-AUC measures ranking across both classes; Brier score measures whether predicted probabilities match observed frequencies.", zh: "在 3.50% 的欺诈率下，准确率具有误导性：把所有交易预测为正常也约有 96.5% 准确率。PR-AUC 评估稀有正类的精确率—召回率权衡；ROC-AUC 衡量两类之间的排序；Brier score 衡量预测概率是否匹配观察频率。" }, implementation: { en: "Call `classification_metrics(y, p)` on validation and untouched test probabilities. Keep the reported metric roles distinct: select and calibrate on validation, then report the final future-like test result once. The reported calibrated-LightGBM test PR-AUC is 0.5728.", zh: "在验证集和未触碰的测试集概率上调用 `classification_metrics(y, p)`。保持指标角色区分：在验证集上选择和校准，再在近似未来的测试集上只报告一次最终结果。报告的校准 LightGBM 测试集 PR-AUC 为 0.5728。" }, business: { en: "Review teams care whether flagged cases are useful; policy teams care whether a 10% score behaves like roughly 10% risk. One metric cannot answer both.", zh: "审核团队关心被标记案例是否有用；策略团队关心 10% 的分数是否大致代表 10% 风险。一个指标无法同时回答两者。" }, formula: { label: { en: "Brier score", zh: "Brier score" }, latex: "\\mathrm{Brier}=\\frac{1}{n}\\sum_{i=1}^{n}(p_i-y_i)^2", explanation: { en: "Lower Brier score means better calibrated probability estimates.", zh: "更低的 Brier score 意味着概率估计校准得更好。" } } },
];

function ProjectWorkflow({ language, steps }: { language: Language; steps: { title: Record<Language, string>; detail: Record<Language, string> }[] }) {
  return <section className="project-workflow-section" aria-labelledby="project-workflow-title"><p className="section-label" id="project-workflow-title">{language === "en" ? "Workflow" : "工作流程"}</p><ol className="project-workflow" aria-label={language === "en" ? "Workflow" : "工作流程"}>{steps.map((step, index) => <li key={step.title.en}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{step.title[language]}</h2><p>{step.detail[language]}</p></div></li>)}</ol></section>;
}

function ProjectLearningGuide({ language, steps }: { language: Language; steps: ProjectLearningStep[] }) {
  return <details className="project-learning-guide" open>
    <summary><span>{language === "en" ? "Learn this project step by step" : "逐步学习这个项目"}</span><small>{language === "en" ? `${steps.length} guided steps` : `${steps.length} 个学习步骤`}</small></summary>
    <div className="project-learning-steps">{steps.map((step, index) => <section key={step.title.en} className="project-learning-step"><p className="section-label">{language === "en" ? `Step ${index + 1}` : `步骤 ${index + 1}`}</p><h2>{step.title[language]}</h2><dl><div><dt>{language === "en" ? "What to learn" : "学习重点"}</dt><dd>{step.learn[language]}</dd></div><div><dt>{language === "en" ? "Try it" : "动手做"}</dt><dd>{step.action[language]}</dd></div><div><dt>{language === "en" ? "Check yourself" : "自我检查"}</dt><dd>{step.check[language]}</dd></div><div className="project-learning-interview"><dt>{language === "en" ? "Why this matters in an interview" : "面试为什么会问"}</dt><dd>{step.interview[language]}</dd></div></dl>{step.code ? <figure className="project-learning-code"><figcaption>{language === "en" ? "Repository code, explained" : "仓库代码与解释"}</figcaption><pre><code>{step.code}</code></pre>{step.codeExplanation ? <p>{step.codeExplanation[language]}</p> : null}</figure> : null}{step.formula ? <MathFormula formula={step.formula} language={language} /> : null}</section>)}</div>
  </details>;
}

function ProjectSystemMap({ language, slug }: { language: Language; slug: string }) {
  if (slug !== "production-fraud-risk-decision-system") return null;
  return <section className="project-system-map" aria-labelledby="project-system-map-title"><p className="section-label">{language === "en" ? "Project map" : "项目地图"}</p><h2 id="project-system-map-title">{language === "en" ? "How the whole project fits together" : "整个项目如何串起来"}</h2><p>{language === "en" ? "Read this once from top to bottom before opening the detailed learning steps below." : "先从上到下读完这张图，再进入下方的详细学习步骤。"}</p><ol>{fraudProjectMap.map((stage) => <li key={stage.title.en}><h3>{stage.title[language]}</h3><dl><div><dt>{language === "en" ? "Input" : "输入"}</dt><dd>{stage.input[language]}</dd></div><div><dt>{language === "en" ? "Work" : "做什么"}</dt><dd>{stage.work[language]}</dd></div><div><dt>{language === "en" ? "Output" : "产出"}</dt><dd>{stage.output[language]}</dd></div></dl></li>)}</ol></section>;
}

function FraudGettingStarted({ language, slug }: { language: Language; slug: string }) {
  if (slug !== "production-fraud-risk-decision-system") return null;
  return <section className="fraud-getting-started" aria-labelledby="fraud-start-title"><p className="section-label">{language === "en" ? "Start here" : "从这里开始"}</p><h2 id="fraud-start-title">{language === "en" ? "What you are building before you write any code" : "写任何代码之前，先知道你要构建什么"}</h2><div><article><h3>{language === "en" ? "The finished system" : "最终系统"}</h3><p>{language === "en" ? "One transaction enters the system. It becomes features, then a calibrated fraud-risk probability, then an approve / review / decline action. The project is successful only if that final action is defensible—not merely if a model has a high score." : "一笔交易进入系统，先变成特征，再变成校准后的欺诈风险概率，最后变成批准/人工审核/拒绝动作。项目成功不只是模型分数高，而是最终动作可辩护。"}</p></article><article><h3>{language === "en" ? "Read the repository in this order" : "按这个顺序阅读仓库"}</h3><ol><li><code>README.md</code> — {language === "en" ? "problem, setup, and results" : "问题、环境与结果"}</li><li><code>src/fraud_ds/data.py</code> + <code>features.py</code> — {language === "en" ? "what the model is allowed to know" : "模型允许知道什么"}</li><li><code>train.py</code> — {language === "en" ? "how fitting and calibration run" : "如何训练和校准"}</li><li><code>metrics.py</code> + <code>policy.py</code> — {language === "en" ? "how scores become decisions" : "分数如何变成决策"}</li><li><code>monitoring.py</code> — {language === "en" ? "how the system stays trustworthy" : "系统如何持续可信"}</li></ol></article><article><h3>{language === "en" ? "The non-negotiable rule" : "不可违反的规则"}</h3><p>{language === "en" ? "At every stage, ask: “Could I have known this at transaction time?” If the answer is no, it cannot be a feature, calibration input, or threshold-tuning signal. This one rule explains why chronological splitting is the foundation of the project." : "每一步都问：“在交易发生时，我能知道这个信息吗？”若答案是否定的，它就不能成为特征、校准输入或调阈值信号。这条规则解释了为什么时间顺序切分是项目基础。"}</p></article></div></section>;
}

function FraudTechnicalTutorial({ language, slug }: { language: Language; slug: string }) {
  if (slug !== "production-fraud-risk-decision-system") return null;
  return <section className="fraud-technical-tutorial" aria-labelledby="fraud-tutorial-title"><p className="section-label">{language === "en" ? "Read and run in this order" : "按此顺序阅读与运行"}</p><h2 id="fraud-tutorial-title">{language === "en" ? "Build the fraud system from zero" : "从零构建欺诈系统"}</h2><p className="fraud-tutorial-intro">{language === "en" ? "Do not skip ahead. Each chapter produces the input required by the next one: data → features → model → calibrated probability → operating decision → monitoring." : "不要跳读。每一章都会产出下一章所需的输入：数据 → 特征 → 模型 → 校准概率 → 运营决策 → 监控。"}</p>{fraudDeepDive.map((module) => <article key={module.title.en}><h3>{module.title[language]}</h3><p className="tutorial-code">{module.code}</p><div><section><h4>{language === "en" ? "What you do" : "你具体做什么"}</h4><p>{module.implementation[language]}</p></section><section><h4>{language === "en" ? "Why it works" : "为什么这样做"}</h4><p>{module.theory[language]}</p></section><section><h4>{language === "en" ? "What it changes for the business" : "它如何影响业务"}</h4><p>{module.business[language]}</p></section></div>{module.formula ? <MathFormula formula={module.formula} language={language} /> : null}</article>)}</section>;
}

export function ProjectDetailPage({ language, slug }: { language: Language; slug: string }) {
  const project = projects.find((item) => item.slug === (legacyProjectSlugs[slug] ?? slug));
  if (!project) return <section className="project-not-found"><p className="section-label">404</p><h1>{language === "en" ? "Project not found" : "未找到该项目"}</h1><p>{language === "en" ? "This project link is not available." : "该项目链接不可用。"}</p><a href="#projects">{language === "en" ? "Back to Projects" : "返回项目页"} ←</a></section>;
  if (project.destination === "external") return <section className="project-not-found"><p className="section-label">{statusLabel.live[language]}</p><h1>{project.title[language]}</h1><p>{project.description[language]}</p><a href={project.externalUrl} target="_blank" rel="noopener noreferrer">{language === "en" ? "Open live portfolio" : "打开在线作品集"} ↗</a></section>;
  const categories = projectCategories.filter((item) => project.categories.includes(item.slug));
  const primaryCategory = categories[0];
  const peers = projects.filter((item) => !item.archived && item.slug !== project.slug && item.categories.some((category) => project.categories.includes(category)));
  const isFraudTutorial = project.slug === "production-fraud-risk-decision-system";
  return <article className="project-detail">
    <a className="back-link" href={primaryCategory ? `#projects/category/${primaryCategory.slug}` : "#projects"}>← {language === "en" ? "Back to Projects" : "返回项目页"}</a>
    <header className={`project-detail-header project-${project.status}`}><p className="section-label">{categories.map((category) => category.title[language]).join(" · ")}</p><p className="project-status">{statusLabel[project.status][language]}</p><h1>{project.title[language]}</h1><p>{project.description[language]}</p><ul className="project-tags" aria-label={language === "en" ? "Methods" : "方法标签"}>{project.methods.map((method) => <li key={method}>{method}</li>)}</ul><div className="project-links">{project.links.map((link) => <a key={link.url} href={link.url} target="_blank" rel="noopener noreferrer">{link.label[language]} <span aria-hidden="true">↗</span></a>)}</div></header>
    {isFraudTutorial ? <FraudTechnicalTutorial language={language} slug={project.slug} /> : <>{project.workflow ? <ProjectWorkflow language={language} steps={project.workflow} /> : null}{projectLearningPaths[project.slug] ? <ProjectLearningGuide language={language} steps={projectLearningPaths[project.slug]} /> : null}<div className="project-detail-body">{project.detailSections.map((section) => <section key={section.title.en}><h2>{section.title[language]}</h2>{section.body.map((paragraph) => <p key={paragraph.en}>{paragraph[language]}</p>)}{section.formulas?.map((item) => <MathFormula key={item.latex} formula={item} language={language} />)}</section>)}{project.interviewTakeaway ? <aside className="project-interview-takeaway"><p className="section-label">{language === "en" ? "Interview talk track" : "面试讲解提示"}</p><p>{project.interviewTakeaway[language]}</p></aside> : null}</div></>}
    <footer className="project-detail-footer">{primaryCategory ? <a href={`#projects/category/${primaryCategory.slug}`}>{language === "en" ? `Explore ${primaryCategory.title.en}` : `浏览${primaryCategory.title.zh}`} →</a> : <a href="#projects">{language === "en" ? "Back to Projects" : "返回项目页"}</a>}{peers.length ? <nav aria-label={language === "en" ? "Related projects" : "相关项目"}>{peers.map((item) => <a key={item.slug} href={`#projects/project/${item.slug}`}>{item.title[language]}</a>)}</nav> : null}</footer>
  </article>;
}
